### ISSUE TITLE
Zeebe Client Go & zbctl

### ISSUE THREAD

**Issue by megglos** [camunda-community-hub/community#159]
# Camunda Community Hub extension proposal

### Extension description
This is the former official Go client and zbctl cli utility migrated to a community project as of https://github.com/camunda/camunda/issues/21817 .

Current state of the client to be migrated to the community hub is here https://github.com/zeebe-io/zeebe-client-go

### Suggested use case
Zeebe client for Go users and cli utility to interact with a zeebe cluster written in Go.

### Dependencies
See https://github.com/megglos/zeebe-client-go/blob/main/go.mod

### Issues/Challenges
Not supporting Camunda 8 REST API but will work while the Zeebe GRPC API is still present.

### Additional context

PDP Epic for deprecation and migration to community project
https://github.com/camunda/product-hub/issues/2438
Slack channel: [#prj-zeebe-go-client-zbctl-deprecation](https://camunda.slack.com/archives/C07L66RECJZ)

### Maintainer eeded?

This extension is actively seeking a maintainer

**Comment by xomiamoore** [comment]
Hi @megglos, I created a new repo for you here and made you maintainer:

https://github.com/camunda-community-hub/zeebe-go-client

If you'd rather transfer the existing repository, we can talk about that too. It's just a little more complicated and we may need IT's help since it's an internal repo and I'm not sure who has the permissions within Camunda to do that transfer.
