### ISSUE TITLE
New community extension(s): C7-/C8-migration support by "Separate your actual business logic from the delegates and all Camunda APIs"

### ISSUE THREAD

**Issue by phactum-at** [camunda-community-hub/community#62]
# C7-/C8-migration support by "Separate your actual business logic from the delegates and all Camunda APIs"

### Extension description

As a Camunda Platinum partner our customers ask about how to migrate to Camunda 8 or how to be prepared to migrate in the future. The best answer we can give is already given by Camunda itself: *Separate your actual business logic from the delegates and all Camunda APIs* (see [migration-guide](https://docs.camunda.io/docs/guides/migrating-from-camunda-platform-7/#prepare-for-smooth-migrations)). We already did this separation as part of customer projects and saw that this is hard for beginners to understand and to establish.

In spring of 2022 we decided to provide this "separation" as a blueprint implementation which can be used by Camunda customers to start right away (either by cloning into their repo or by using this as a Maven dependency): https://github.com/phactum/taxiride-blueprint/tree/old_including_spi_and_adapters. The result is ideal for beginners and once they know about the principles the folks also can learn about the details. We used it in one customer project as a proof of concept. There is also a [public demo](https://github.com/phactum/variable-less-blueprint). Two more customer projects started right now and we are about to release the BP- and Camunda-migration-stuff of our blueprint and will name it "VanillaBP".

The blueprint project was not only about migrating Camunda 7 to 8 but also about building Spring Boot based (micro-)services with API-first REST-APIs. VanillaBP is only about the BP- and migration-stuff and the rest will remain in the blueprint project: https://github.com/phactum/taxiride-blueprint. To be able to use Camunda 7 and Camunda 8 without modifications of the business code we introduced adapters for either [Camunda 7](https://github.com/vanillabp/camunda7-adapter) and [Camunda 8](https://github.com/vanillabp/camunda8-adapter). We would be very glad to have the Camunda adapters we developed for easy 7/8 migration hosted on Camunda Community Hub! Therefore we would like to move those adapters in two separate Camunda community hub projects.

We had a [talk at Camunda Summit 2022](https://page.camunda.com/ccs2022-goodbyetoprocessvariables) about some aspects and Luc Weinbrecht had a [talk about the archectural aspects at CamundaCon 2022](https://page.camunda.com/camundacon-2022-envite-consulting). These adapters are concrete implemenations of the *Separate your actual business logic from the delegates and all Camunda APIs* hint (see [migration-guide](https://docs.camunda.io/docs/guides/migrating-from-camunda-platform-7/#prepare-for-smooth-migrations)) ready to be used as we do in our customer projects.

### Suggested use case

Separate your actual business logic from the delegates and all Camunda APIs for easy C7/C8 migration.

### Configuration

The respective adapter is a Maven-dependency (see [public demo](https://github.com/phactum/variable-less-blueprint/blob/main/pom.xml#L115)). Currently, only Spring Boot is supported, so everything is configured via Spring-autoconfiguration. As the adapters use Camunda's standard Spring boot connectors for C7 and C8 configuration we typically use two different [Spring boot profiles](https://github.com/phactum/variable-less-blueprint/tree/main/src/it/resources/config), but besides that there is no additional configuration.

### Dependencies

* Java 11
* C7 adapter:
   * camunda-bpm-spring-boot-starter-webapp (tested with Camunda 7.17 but might work also with previous versions)
   * [VanillaBP abstract adapter implementation for Spring Boot](https://github.com/vanillabp/spring-boot-support)
* C8 adapter:
   * spring-zeebe-starter (tested with 8.1.13 and will be tested with the current before release)
   * [VanillaBP abstract adapter implementation for Spring Boot](https://github.com/vanillabp/spring-boot-support)

### Issues/Challenges

Hopefully none, since this should make things much easier ;-)

### Extension lifecycle

I guess the best fit is

[![](https://img.shields.io/badge/Lifecycle-Incubating-blue)](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#incubating-)

### Additional context

The [VanillaBP SPI](https://github.com/vanillabp/spi-for-java) which shows how business code will look like.

### Maintainer needed?

No

**Comment by phactum-at** [comment]
I unintendendly created this issue using my company account. Can you add me [stephanpelikan](https://github.com/stephanpelikan) as a participant?

**Comment by stephanpelikan** [comment]
Hi guys,

I have a Talk on the Camunda Vienna Meetup on 31st on January (https://community.camunda.com/events/details/camunda-camunda-chapter-vienna-presents-dive-with-us-into-camundacon-2022-c8-connector-sdk-and-c8-readiness/) in which I would like to show this already as a public available Camunda extension on Camunda Community Hub.

Will we make this? Can you process my request this week? Once you confirm, I would adapt those two projects (Java package, Maven groupId, change README according to Hub requirements) transfer them and afterwards release them. So, there is a lot of work pending ;-)

Thx, Stephan

**Comment by xomiamoore** [comment]
Hi @stephanpelikan! Apologies for the delay, we would love to have these extensions in the Community Hub!

[Please follow these steps](https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) for transferring the repos into the Camunda Community Hub and let me know if there are any other questions!

**Comment by stephanpelikan** [comment]
Hi,

I just transfered those two repos:

- https://github.com/camunda-community-hub/vanillabp-camunda7-adapter
- https://github.com/camunda-community-hub/vanillabp-camunda8-adapter

Can you now configure me as a maintainer? Also it would be great if my avatar is shown up as a contributor :wink:

Currently I'm able to push changes but next I would like to configure releasing, so I can publish these artifacts. Afterwards I would like to protect the "main" branch, so changes can only be done by creating pull-requests.

On additional question: Currently, the artifacts Maven version is 0.0.1-SNAPSHOT. Do I have to change this to 1.0.0 before releasing and change it to 1.0.1-SNAPSHOT after releasing or is this done as part of the Github release action?

Thx, Stephan

**Comment by xomiamoore** [comment]
Awesome! I added you as maintainer for both repos. You should be able to configure your branch protections and releases now.

I'm not sure how to get the "Contributors" category to show up on the right sidebar 🤔 Maybe there needs to be more than one contributor for that to show?

I'm not an expert in Maven, but I believe you should update it before releasing to:

```
<parent>
    <groupId>org.camunda.community</groupId>
    <artifactId>community-hub-release-parent</artifactId>
    <version>1.3.1</version>
</parent>
```

**Comment by stephanpelikan** [comment]
Unfortunately, I cannot push any more! Neither on the main branch nor on creating a new branch :worried:

Can you fix that soon?

**Comment by stephanpelikan** [comment]
I talked to a friend of mine @martinschimak who is the creator of [Camunda Platform Scenario](https://github.com/camunda-community-hub/camunda-platform-scenario) and he is also not able administrate details of his repo.

We compared the appearances of our repors and there is only one obvious difference:
![scenario_headline](https://user-images.githubusercontent.com/5190548/213388365-83662a7d-435c-4fb5-98df-e3f7528348d6.png)
This *discussions* headline is missing in my repos. Since I not even now what this is about in detail, it doesn't matter for now.

But, what I'm missing is
1. That I cannot push code any more
2. I cannot select the default branch and protect branches as I can do in non-Community-Hub projects: ![github_branches](https://user-images.githubusercontent.com/5190548/213388309-45f57279-6b7c-457e-8474-f0c1523aeb0c.png)

I plan to release my two extensions and afterwards I want to protect the *main* branch. By-the-way: I already added the release-parent in my pom.xml files and Martin could clearify the version-issues I asked you for. So, I know about it now.

**Comment by xomiamoore** [comment]
Okay, I changed your permissions to Admin as that is required for the branch protection settings and a few important security settings. (More on [GitHub permissions here](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role))

However, you shouldn't need Admin access to push code, so I'm still looking into that. 🕵🏻

**Comment by akeller** [comment]
@stephanpelikan 👋  I'm assisting Mia with the permissions issues you are facing. I'm curious about your issues with pushing. Did you get an error? Were you using a Git client or the command line? 

We assume this will go away now that you are an Admin, but I'm wondering if you are running into issues because of your personal and company accounts. 

Now that the repo is part of the Camunda Community Hub the remote org location has changed, but your local settings may not have you logged in to your personal account. If you are trying to push but logged into the company account, I expect you **not** to be able to push since the company account does not have Write (or Admin!) access. This is a theory somewhat based on what's happening in [this thread](https://github.com/orgs/community/discussions/27305#discussioncomment-3281574).

**Comment by stephanpelikan** [comment]
Hi,

after transfering to Hub I changed to remote of my project;

```
$ git remote -v
origin	https://stephanpelikan@github.com/camunda-community-hub/vanillabp-camunda7-adapter.git (fetch)
origin	https://stephanpelikan@github.com/camunda-community-hub/vanillabp-camunda7-adapter.git (push)
```

and was able to push changes using @stephanpelikan as I mentioned in https://github.com/camunda-community-hub/community/issues/62#issuecomment-1386781085. In this comment I asked to make me a maintainer for my transfered repositories. After that I tried to introduce deploy.yaml and was not able to push any more (403 forbidden). Unfortunately, I didn't share the exact output :worried: .

Now, as you changed permissions, I see a different error:
```
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/deploy.yaml` without `workflow` scope)
```

This is something I could deal with by creating a new personal token having the required scope. Now I'm able to push.

I will go ahead with releasing and will reach out again once that's done :thumbsup:

**Comment by akeller** [comment]
Thanks @stephanpelikan and so sorry you are dealing with this! Glad to hear you are able to push now.

**Comment by stephanpelikan** [comment]
Hi,

my release failed due to a missing secret key: https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/actions/runs/3968716506/jobs/6802250126
This seems to be exactly what is mentioned at: https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD#what-if-my-release-says-its-missing-a-key-for-gpg

But I compare the example to my deploy.yaml and it seems to be the same regarding gpg:

- example: https://github.com/camunda-community-hub/community-action-maven-release/blob/22004c20cb61979859e889cf17081b3e886849b8/example-workflows/java11/deploy.yml#L25-L30
- mine: https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/blob/main/.github/workflows/deploy.yaml#L13-L20).
- 
What is missing?

**Comment by xomiamoore** [comment]
@stephanpelikan, I gave you access to the secrets for both repos, so that should solve at least some of the issues. 

I'm not sure about `Unexpected input(s) 'maven-auto-release-after-close', valid inputs are ['artifacts-pattern', 'run-tests', 'maven-additional-options',...:` -- can you try running again now that I've given the secrets to see if it still happens?

**Comment by stephanpelikan** [comment]
Hi,

now I could run the action successfully!

- vanillabp-camunda7-adapter: [v1.0.0](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/releases/tag/1.0.0)
- vanillabp-camunda8-adapter: [v1.0.0](https://github.com/camunda-community-hub/vanillabp-camunda8-adapter/releases/tag/1.0.0)

Unfortunately, I had an issue regarding my javadoc, so I had to create a third release:

- vanillabp-camunda7-adapter: [v1.0.1](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/releases/tag/1.0.1)

I also created those "release issues" for all my releases and assign them according to your [RELEASE.md](https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD):
- https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/issues/1
- https://github.com/camunda-community-hub/vanillabp-camunda8-adapter/issues/1

There are still warnings in the [action's log](https://github.com/camunda-community-hub/vanillabp-camunda7-adapter/actions/runs/3978659229):
- Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-release-asset@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
- Unexpected input(s) 'maven-auto-release-after-close', valid inputs are ['artifacts-pattern', 'run-tests', 'maven-additional-options', 'maven-release-options', 'release-version', 'release-profile', 'central-release-profile', 'nexus-usr', 'nexus-psw', 'maven-usr', 'maven-psw', 'maven-gpg-passphrase', 'github-token', 'maven-build-options', 'vulnerability-scan', 'maven-url', 'branch']
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I will create issues for this in the [community-action-maven-release repository](https://github.com/camunda-community-hub/community-action-maven-release).

Since this overall process of onboarding took so long, I'm now facing the situation that I need this release for a customer workshop tomorrow at 8:30am CET. Since your are answering in this conversation only from 9-12pm CET I guess you are located in the USA. **I hope you will see my release-issues already today and will publish my releases to Maven-Central before my workshop!**.

Thx, Stephan

**Comment by stephanpelikan** [comment]
@NPDeehan : Thanky you Naill for jumping in! I now had the first part of that workshop and could retrieve the dependency from Maven-Central. So everything is great 👍
